nice -n 20 /home/heather/.conda/envs/bproc/bin/python -m infinigen_examples.generate_auv_mission -- --output_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/coarse --seed 53b350c9 --task coarse --task_uniqname coarse -g coral_reef coral_reef_hd.gin -p LOG_DIR='/home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/logs' execute_tasks.frame_range=[1, 8] execute_tasks.camera_id=[0, 0]

nice -n 20 /home/heather/.conda/envs/bproc/bin/python -m infinigen_examples.generate_auv_mission -- --input_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/coarse --output_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/fine --seed 53b350c9 --task fine_terrain --task_uniqname fineterrain -g coral_reef coral_reef_hd.gin -p LOG_DIR='/home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/logs' Terrain.device='cuda' execute_tasks.frame_range=[1, 8] execute_tasks.camera_id=[0, 0]

nice -n 20 /home/heather/.conda/envs/bproc/bin/python -m infinigen_examples.generate_auv_mission -- --input_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/fine --output_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/fine --seed 53b350c9 --task populate --task_uniqname populate -g coral_reef coral_reef_hd.gin -p LOG_DIR='/home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/logs' execute_tasks.frame_range=[1, 3] execute_tasks.camera_id=[0, 0]

nice -n 20 /home/heather/.conda/envs/bproc/bin/python -m infinigen_examples.generate_auv_mission -- --input_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/fine --output_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/frames_0_0_0001_1 --seed 53b350c9 --task render --task_uniqname rendershort_0_0_0001_1 -g coral_reef coral_reef_hd.gin -p render.render_image_func=@full/render_image LOG_DIR='/home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/logs' execute_tasks.frame_range=[1,3] execute_tasks.camera_id=[0,1] execute_tasks.resample_idx=0

nice -n 20 /home/heather/.conda/envs/bproc/bin/python -m infinigen_examples.generate_auv_mission -- --input_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/fine --output_folder /home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/frames_0_0_0001_1 --seed 53b350c9 --task render --task_uniqname blendergt_0_0_0001_1 -g coral_reef coral_reef_hd.gin -p render.render_image_func=@flat/render_image LOG_DIR='/home/heather/GitHub/infinigen/outputs/nimbusv3/53b350c9/logs' execute_tasks.frame_range=[1,3] execute_tasks.camera_id=[0,1] execute_tasks.resample_idx=0
